export const employerDemo = {
    stats: [
        { label: 'Total Employers', value: '2,847', tone: 'text-[#0057c8]' },
        { label: 'Active Employers', value: '2,341', tone: 'text-[#10b981]' },
        { label: 'Pending Employers', value: '312', tone: 'text-[#e57124]' },
        { label: 'Suspended Employers', value: '143', tone: 'text-[#ef4444]' },
        { label: 'Rejected Employers', value: '51', tone: 'text-[#64748b]' },
    ],
    rows: [
        {
            id: 'EMP-001',
            name: 'Emirates Tech Solutions',
            industry: 'Technology',
            contact: 'Omar Hassan',
            email: 'omar@emiratestech.ae',
            verification: 'Approved',
            package: 'Enterprise',
            jobs: 24,
            date: '2024-01-12',
            status: 'Active',
        },
        {
            id: 'EMP-002',
            name: 'Gulf Construction Co.',
            industry: 'Construction',
            contact: 'Sara Al-Mansoori',
            email: 'sara@gulfconst.ae',
            verification: 'Pending',
            package: 'Professional',
            jobs: 8,
            date: '2024-02-03',
            status: 'Pending Verification',
        },
        {
            id: 'EMP-003',
            name: 'Desert Finance Group',
            industry: 'Finance',
            contact: 'Khalid Nasser',
            email: 'khalid@desertfinance.ae',
            verification: 'Approved',
            package: 'Premium',
            jobs: 15,
            date: '2024-01-28',
            status: 'Active',
        },
        {
            id: 'EMP-004',
            name: 'Nova Retail LLC',
            industry: 'Retail',
            contact: 'Lina Farouk',
            email: 'lina@novaretail.ae',
            verification: 'Rejected',
            package: 'Starter',
            jobs: 0,
            date: '2024-03-01',
            status: 'Rejected',
        },
        {
            id: 'EMP-005',
            name: 'Apex Logistics',
            industry: 'Logistics',
            contact: 'Yousef Karim',
            email: 'yousef@apexlog.ae',
            verification: 'Approved',
            package: 'Professional',
            jobs: 11,
            date: '2024-02-18',
            status: 'Active',
        },
        {
            id: 'EMP-006',
            name: 'Bright Health Clinics',
            industry: 'Healthcare',
            contact: 'Nadia Rahim',
            email: 'nadia@brighthealth.ae',
            verification: 'Pending',
            package: 'Starter',
            jobs: 3,
            date: '2024-03-08',
            status: 'Pending Verification',
        },
        {
            id: 'EMP-007',
            name: 'Horizon Media',
            industry: 'Media',
            contact: 'Faisal Qasim',
            email: 'faisal@horizonmedia.ae',
            verification: 'Approved',
            package: 'Enterprise',
            jobs: 19,
            date: '2024-01-05',
            status: 'Active',
        },
    ],
};

export const jobSeekerDemo = {
    stats: [
        { label: 'Total Job Seekers', value: '48,291', tone: 'text-[#0057c8]' },
        { label: 'Active Job Seekers', value: '41,204', tone: 'text-[#e57124]' },
        {
            label: 'Suspended Job Seekers',
            value: '892',
            tone: 'text-[#0057c8]',
        },
        {
            label: 'Inactive Job Seekers',
            value: '6,195',
            tone: 'text-[#64748b]',
        },
    ],
    rows: [
        {
            id: 'JS-001',
            name: 'Rania Ahmed',
            email: 'rania@email.com',
            phone: '+971 50 111 2222',
            location: 'Dubai, UAE',
            applications: 12,
            resume: 'Active',
            date: '2024-01-10',
            status: 'Active',
        },
        {
            id: 'JS-002',
            name: 'Ali Khan',
            email: 'ali.khan@email.com',
            phone: '+971 55 333 4444',
            location: 'Abu Dhabi, UAE',
            applications: 5,
            resume: 'Warning',
            date: '2024-02-14',
            status: 'Inactive',
        },
        {
            id: 'JS-003',
            name: 'Mariam Hassan',
            email: 'mariam.h@email.com',
            phone: '+971 52 555 6666',
            location: 'Sharjah, UAE',
            applications: 21,
            resume: 'Active',
            date: '2024-01-22',
            status: 'Active',
        },
        {
            id: 'JS-004',
            name: 'Omar Saleh',
            email: 'omar.s@email.com',
            phone: '+971 54 777 8888',
            location: 'Dubai, UAE',
            applications: 2,
            resume: 'Active',
            date: '2024-03-02',
            status: 'Suspended',
        },
        {
            id: 'JS-005',
            name: 'Layla Nour',
            email: 'layla.n@email.com',
            phone: '+971 56 999 0000',
            location: 'Ajman, UAE',
            applications: 9,
            resume: 'Active',
            date: '2024-02-01',
            status: 'Active',
        },
        {
            id: 'JS-006',
            name: 'Hassan Farid',
            email: 'hassan.f@email.com',
            phone: '+971 50 222 3333',
            location: 'Dubai, UAE',
            applications: 0,
            resume: 'Warning',
            date: '2024-03-11',
            status: 'Inactive',
        },
        {
            id: 'JS-007',
            name: 'Noor Yasin',
            email: 'noor.y@email.com',
            phone: '+971 58 444 5555',
            location: 'Al Ain, UAE',
            applications: 14,
            resume: 'Active',
            date: '2024-01-30',
            status: 'Active',
        },
    ],
};

export const jobDemo = {
    stats: [
        { label: 'Total Jobs', value: '9,847', tone: 'text-[#0057c8]' },
        { label: 'Active Jobs', value: '5,124', tone: 'text-[#e57124]' },
        { label: 'Pending Jobs', value: '134', tone: 'text-[#f59e0b]' },
        { label: 'Rejected Jobs', value: '482', tone: 'text-[#ef4444]' },
        { label: 'Expired Jobs', value: '3,891', tone: 'text-[#64748b]' },
        { label: 'Active Jobs', value: '89', tone: 'text-[#0ea5e9]' },
        { label: 'Reported Jobs', value: '12', tone: 'text-[#c2410c]' },
    ],
    rows: [
        {
            id: 'JOB-1842',
            title: 'Senior React Developer',
            employer: 'Emirates Tech Solutions',
            category: 'Technology',
            location: 'Dubai',
            applications: 48,
            views: 1204,
            status: 'Active',
            created: '2024-03-01',
        },
        {
            id: 'JOB-1841',
            title: 'Site Engineer',
            employer: 'Gulf Construction Co.',
            category: 'Construction',
            location: 'Abu Dhabi',
            applications: 22,
            views: 640,
            status: 'Pending',
            created: '2024-03-08',
        },
        {
            id: 'JOB-1838',
            title: 'Financial Analyst',
            employer: 'Desert Finance Group',
            category: 'Finance',
            location: 'Dubai',
            applications: 31,
            views: 890,
            status: 'Active',
            created: '2024-02-26',
        },
        {
            id: 'JOB-1835',
            title: 'Store Manager',
            employer: 'Nova Retail LLC',
            category: 'Retail',
            location: 'Sharjah',
            applications: 12,
            views: 310,
            status: 'Rejected',
            created: '2024-02-20',
        },
        {
            id: 'JOB-1830',
            title: 'Logistics Coordinator',
            employer: 'Apex Logistics',
            category: 'Logistics',
            location: 'Dubai',
            applications: 17,
            views: 455,
            status: 'Active',
            created: '2024-02-12',
        },
        {
            id: 'JOB-1824',
            title: 'Registered Nurse',
            employer: 'Bright Health Clinics',
            category: 'Healthcare',
            location: 'Ajman',
            applications: 40,
            views: 980,
            status: 'Pending',
            created: '2024-03-10',
        },
        {
            id: 'JOB-1819',
            title: 'Content Producer',
            employer: 'Horizon Media',
            category: 'Media',
            location: 'Dubai',
            applications: 9,
            views: 220,
            status: 'Expired',
            created: '2023-12-15',
        },
    ],
};
